php:
  container_name: php5
  build: .
  links:
    - db
  ports:
    - "8086:80"
    - "8089:443"
  volumes:
    - ./www:/var/www/html
db:
  container_name: db5
  image: mariadb
  ports:
    - "8088:3306"
  environment:
    MYSQL_ROOT_PASSWORD: root
    MYSQL_USER: root
    MYSQL_PASSWORD: root
phpmyadmin:
 container_name: phpmyadmin5
 image: phpmyadmin/phpmyadmin
 links:
   - db
 ports:
   - "8087:80"    